[tool.poetry]
name = "borsdata-sdk"
version = "0.1.0"
description = ""
authors = ["murre <43014508+figge215@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
